### ISSUE TITLE
Running "yarn dev" on the vite template results in 46+ "Could not resolve" errors

### ISSUE THREAD

**Issue by m6io** [bonfhir/bonfhir#265]
The vite template seems to be missing something in it's configuration. I'm using it as instructed from the docs.

<img width="464" alt="image" src="https://github.com/bonfhir/bonfhir/assets/147613092/fbf65909-7a2a-443c-99c4-9ec835de59bc">

**Comment by m6io** [comment]
For other devs that are interested in using this: don't bother. The maintainers don't respond. This project is vaporware.

**Comment by lp** [comment]
@m6io I could reproduced the bug you submitted, thanks for reporting.

The problem is with one upstream dependency `mantine`, which _peerDependency_ `dayjs` seems to be missing in a `yarn` environment.

The `npm` based package management doesn't suffer from the same issue.
Choosing `npm` instead of `yarn` should provide a workaround.

**Comment by opiation** [comment]
Indeed, `@mantine/dates` [defines `dayjs` as a peer dependency](https://github.com/mantinedev/mantine/blob/b95051c4fce1b8fd49efa5816a3dc2e91e93ae4f/packages/%40mantine/dates/package.json#L50) and [instructs users of the library to install `dayjs` separately](https://mantine.dev/dates/getting-started/).

Since the Vite template installs `@mantine/dates` (though not initially using it anywhere), I think the Vite template should also install `dayjs` as a dependency or remove the `@mantine/dates` dependency entirely, leaving it to the user to do so. My preference is for the Vite template to add `dayjs` since that seems more appropriate for a starter template to do.

@lp, would you agree or recommend a different solution?

**Comment by opiation** [comment]
This seemed like a quick fix so I couldn't resist -> #286. Turned out to be a few other peer dependencies in the Next and Vite templates that needed to be added to get the dev server to startup without warnings or errors under Yarn.

**Comment by opiation** [comment]
The fix for this has been merged. Stay tuned for releases published after today including this fix.

**Comment by opiation** [comment]
This should be fixed with [`@bonfhir/cli` >= 2.12.2](https://github.com/bonfhir/bonfhir/releases/tag/%40bonfhir%2Fcli%402.12.2). Create a new Bonfhir project with Vite and Yarn and running `yarn dev` now works for me. @m6io, feel free to respond if you're still getting this error.
