### ISSUE TITLE
Explore https://ui.shadcn.com/ as a renderer 

### ISSUE THREAD

**Issue by ysael** [bonfhir/bonfhir#66]

**Comment by julienblin** [comment]
For our designers I compiled a list of component usage for `ui-mantine`, if you want to check feature parity with shadcdn:

- [FhirTable](https://bonfhir.dev/storybook/?path=/docs/bonfhir-data-display-fhirtable--docs):
    - [Table](https://mantine.dev/core/table/)
    - [UnstyledButton](https://mantine.dev/core/unstyled-button/) (for sorting icons on table headers)
- [FhirValue](https://bonfhir.dev/storybook/?path=/docs/bonfhir-data-display-fhirvalue--docs)
    - [Text](https://mantine.dev/core/text/)
- [FhirError](https://bonfhir.dev/storybook/?path=/docs/bonfhir-feedback-fhirerror--docs)
    - [Alert](https://mantine.dev/core/alert/)
    - [ActionIcon](https://mantine.dev/core/action-icon/)
- [FhirQueryLoader](https://bonfhir.dev/storybook/?path=/docs/bonfhir-feedback-fhirqueryloader--docs)
    - [Loader](https://mantine.dev/core/loader/)
- [FhirInput](https://bonfhir.dev/storybook/?path=/docs/bonfhir-inputs-fhirinput--docs)
    - [Checkbox](https://mantine.dev/core/checkbox/)
    - [Switch](https://mantine.dev/core/switch/)
    - [DateTimePicker](https://mantine.dev/dates/date-time-picker/)
    - [DateInput](https://mantine.dev/dates/date-input/)
    - [TimeInput](https://mantine.dev/dates/time-input/)
    - [Select](https://mantine.dev/core/select/)
    - [RichTextEditor](https://mantine.dev/others/tiptap/)
    - [NumberInput](https://mantine.dev/core/number-input/)
    - [TextInput](https://mantine.dev/core/text-input/)
    - [TextArea](https://mantine.dev/core/textarea/)
    - [Radio](https://mantine.dev/core/radio/)
    - [SegmentedControl](https://mantine.dev/core/segmented-control/)
- [FhirInputArray](https://bonfhir.dev/storybook/?path=/docs/bonfhir-inputs-fhirinputarray--docs)
    - [ActionIcon](https://mantine.dev/core/action-icon/)
    - [Input](https://mantine.dev/core/input/)
- [FhirQuestionnaire](https://bonfhir.dev/storybook/?path=/docs/bonfhir-inputs-fhirquestionnaire--docs): Combination of all the others, don't worry about this one (yet :-))
- FhirPagination
    - [Pagination](https://mantine.dev/core/pagination/)

**Comment by jckw** [comment]
I'm interested in this too. shadcn/ui is probably the nicest way to work with components right now due to the fact that you are just importing code which you can then modify.

I think if bonFHIR is going to implement shadcn/ui, it should focus on implementing the UI components in the same way. 
I.e., as a dev working with bonFHIR, I can import the code for a FhirTable and modify it directly in the same codebase that I'm working in, instead of having to import it from bonFHIR itself. bonFHIR's UI library would therefore be "installed" via code generation as an extension to the shadcn/ui method. That way, UI components don't need to be configured with large amounts of props, and themes etc. but can be edited directly.

I imagine that the way it would work is that for each bonFHIR component, the component's code can easily be copied into a project and refers to the same shadcn/ui components that exist elsewhere. That may be too much of a change for this repo.

Here's a table of analogous components anyway. I think the important thing to note is that things not existing just means a small amount of implementation work from other shadcn components.

| Bonfhir Component | Mantine Component                                               | Shadcn Component                                                                                |
| ----------------- | --------------------------------------------------------------- | ----------------------------------------------------------------------------------------------- |
| FhirTable         | [Table](https://mantine.dev/core/table/)                        | https://ui.shadcn.com/docs/components/table or https://ui.shadcn.com/docs/components/data-table |
|                   | [UnstyledButton](https://mantine.dev/core/unstyled-button/)     | https://ui.shadcn.com/docs/components/button                                                    |
| FhirValue         | [Text](https://mantine.dev/core/text/)                          | Doesn't exist                                                                                   |
| FhirError         | [Alert](https://mantine.dev/core/alert/)                        | https://ui.shadcn.com/docs/components/alert                                                     |
|                   | [ActionIcon](https://mantine.dev/core/action-icon/)             | Doesn't exist, but easy enough with SVGs                                                        |
| FhirQueryLoader   | [Loader](https://mantine.dev/core/loader/)                      | Doesn't exist, but easy enough with SVGs                                                        |
| FhirInput         | [Checkbox](https://mantine.dev/core/checkbox/)                  | https://ui.shadcn.com/docs/components/checkbox                                                  |
|                   | [Switch](https://mantine.dev/core/switch/)                      | https://ui.shadcn.com/docs/components/switch                                                    |
|                   | [DateTimePicker](https://mantine.dev/dates/date-time-picker/)   | Doesn't exist                                                                                   |
|                   | [DateInput](https://mantine.dev/dates/date-input/)              | https://ui.shadcn.com/docs/components/date-picker                                               |
|                   | [TimeInput](https://mantine.dev/dates/time-input/)              | Doesn't exist                                                                                   |
|                   | [Select](https://mantine.dev/core/select/)                      | https://ui.shadcn.com/docs/components/select                                                    |
|                   | [RichTextEditor](https://mantine.dev/others/tiptap/)            | Doesn't exist, but would need to be implemented with https://tiptap.dev/ or similar                                                                       |
|                   | [NumberInput](https://mantine.dev/core/number-input/)           | https://ui.shadcn.com/docs/components/input                                                     |
|                   | [TextInput](https://mantine.dev/core/text-input/)               | https://ui.shadcn.com/docs/components/input                                                     |
|                   | [TextArea](https://mantine.dev/core/textarea/)                  | https://ui.shadcn.com/docs/components/textarea                                                  |
|                   | [Radio](https://mantine.dev/core/radio/)                        | https://ui.shadcn.com/docs/components/radio-group                                               |
|                   | [SegmentedControl](https://mantine.dev/core/segmented-control/) | https://ui.shadcn.com/docs/components/tabs                                                      |
| FhirInputArray    | [ActionIcon](https://mantine.dev/core/action-icon/)             | Doesn't exist, but easy enough with SVGs                                                        |
|                   | [Input](https://mantine.dev/core/input/)                        | https://ui.shadcn.com/docs/components/input                                                     |
| FhirPagination    | [Pagination](https://mantine.dev/core/pagination/)              | https://ui.shadcn.com/docs/components/pagination                                                                                   |

**Comment by lvancraen** [comment]
hey @ysael, do you mind writing up your conclusion on your findings for this ticket? I'd like to either close it or move it along. Given bonfhir has also implemented mantine components, if this ticket is no longer relevant, please close it. Thanks!

**Comment by julienblin** [comment]
I am closing due to the lack of activity. We will reopen later if we find a need and resources to work on it.
