### ISSUE TITLE
Odd behavior of `this` when using `extendResource` with a `get` accessor

### ISSUE THREAD

**Issue by biximilien** [bonfhir/bonfhir#70]
I'm seeing this odd behavior when trying to add a get accessor to an extended resource.

This code doesn't work, the value of `this.birthDate` is always `undefined`

```
export const CustomPatient = extendResource("Patient", {
  get age(): number | undefined {
    if (this.birthDate) {
      const birthDate = parse(this.birthDate, "yyyy-mm-dd", new Date());
      const { years } = intervalToDuration({
        start: birthDate,
        end: new Date(),
      });
      return years;
    }
    return undefined;
  },
});
```

To work around, I remove the accessor:

```
export const CustomPatient = extendResource("Patient", {
 getAge(): number | undefined {
    log.debug(`Patient: ${this}`); // [object Object]
    log.debug(`Birthdate: ${this.birthDate}`); // undefined
    if (this.birthDate) {
      const birthDate = parse(this.birthDate, "yyyy-mm-dd", new Date());
      const { years } = intervalToDuration({
        start: birthDate,
        end: new Date(),
      });
      return years;
    }
    return undefined;
  },
});
```

I would expect both to work.

**Comment by julienblin** [comment]
Thanks @biximilien!

Yes, properties do not work in extended resources proxies at the moment - this is due to how the extension is built and should be properly documented.

This is also an interesting date calculation here that points out a missing piece in the duration API - there is nothing to round durations to the closes unit. For now, it can only do this:

```typescript
const age = duration.from(today(), this.birthDate);
```

But this probably will return a duration in days. We are missing a round API in duration. Will create a ticket now.
